# Configurable environment variables:
# HAB_ORIGIN - denotes the docker origin (dockerhub ID)
# VERSION -  the version identifier tag on the packages
# HOST_IP - the IP address of the docker host. 172.17.0.1 is commonly the docker0 interface which is fine
# ENTERPRISE - the name of the Automate enterprise to create
# ADMIN_PASSWORD - the initial password to set for the 'admin' user in the Automate UI
# AUTOMATE_TOKEN - the token for the Automate server data collector
# DATA_MOUNT - the mount point for the data
# USER_ID - the user ID to use

version: '2.1'
services:
  postgresql:
    image: ${HAB_ORIGIN:-chefservernonroot}/postgresql:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    environment:
      HAB_POSTGRESQL: |
        [superuser]
        name = 'hab'
        password = 'chefrocks'
    volumes:
      - ${DATA_MOUNT:-/mnt/hab}/postgresql:/hab/svc/postgresql/data:Z

  rabbitmq:
    image: ${HAB_ORIGIN:-chefservernonroot}/rabbitmq:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    command: --peer ${HOST_IP:-172.17.0.1}
      --listen-gossip 0.0.0.0:9650
      --listen-http 0.0.0.0:9660
    depends_on:
      - postgresql
    environment:
      HAB_RABBITMQ: |
        [rabbitmq]
        default_vhost = '/insights'
        default_user = 'insights'
        default_pass = 'chefrocks'
        [rabbitmq.management]
        enabled = true
    volumes:
      - ${DATA_MOUNT:-/mnt/hab}/rabbitmq:/hab/svc/rabbitmq/data:Z

  elasticsearch:
    image: ${HAB_ORIGIN:-chefservernonroot}/elasticsearch:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    command: --peer ${HOST_IP:-172.17.0.1}
      --listen-gossip 0.0.0.0:9651
      --listen-http 0.0.0.0:9661
    depends_on:
      - postgresql
    volumes:
      - ${DATA_MOUNT:-/mnt/hab}/elasticsearch:/hab/svc/elasticsearch/data:Z

  logstash:
    image: ${HAB_ORIGIN:-chefservernonroot}/logstash:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    command: --peer ${HOST_IP:-172.17.0.1}
      --bind elasticsearch:elasticsearch.default
      --bind rabbitmq:rabbitmq.default
      --listen-gossip 0.0.0.0:9652
      --listen-http 0.0.0.0:9662
    depends_on:
      - postgresql

  workflow-server:
    image: ${HAB_ORIGIN:-chefservernonroot}/workflow-server:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    command: --peer ${HOST_IP:-172.17.0.1}
      --bind database:postgresql.default
      --bind elasticsearch:elasticsearch.default
      --bind rabbitmq:rabbitmq.default
      --listen-gossip 0.0.0.0:9653
      --listen-http 0.0.0.0:9663
    depends_on:
      - postgresql
    environment:
      HAB_WORKFLOW_SERVER: |
        enterprise = '${ENTERPRISE:-default}'
        default_admin_password = '${ADMIN_PASSWORD:-chefrocks}'

        [data_collector]
        token = "${AUTOMATE_TOKEN:-93a49a4f2482c64126f7b6015e6b0f30284287ee4054ff8807fb63d9cbd1c506}"
    volumes:
      - ${DATA_MOUNT:-/mnt/hab}/maintenance:/var/opt/delivery/delivery/etc:Z
      - ${DATA_MOUNT:-/mnt/hab}/workflow:/hab/svc/workflow-server/data:Z

  notifications:
    image: ${HAB_ORIGIN:-chefservernonroot}/notifications:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    command: --peer ${HOST_IP:-172.17.0.1}
      --bind elasticsearch:elasticsearch.default
      --bind rabbitmq:rabbitmq.default
      --listen-gossip 0.0.0.0:9654
      --listen-http 0.0.0.0:9664
    depends_on:
      - postgresql

  compliance:
    image: ${HAB_ORIGIN:-chefservernonroot}/compliance:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    command: --peer ${HOST_IP:-172.17.0.1}
      --bind elasticsearch:elasticsearch.default
      --listen-gossip 0.0.0.0:9655
      --listen-http 0.0.0.0:9665
    depends_on:
      - postgresql
    volumes:
      - ${DATA_MOUNT:-/mnt/hab}/compliance:/hab/svc/compliance/data:Z

  automate-nginx:
    image: ${HAB_ORIGIN:-chefservernonroot}/automate-nginx:${VERSION:-latest}
    network_mode: host
    restart: always
    user: ${USER_ID:-42}
    cap_drop:
    - NET_BIND_SERVICE
    - SETUID
    - SETGID
    command: --peer ${HOST_IP:-172.17.0.1}
      --bind compliance:compliance.default
      --bind elasticsearch:elasticsearch.default
      --bind workflow:workflow-server.default
      --bind notifications:notifications.default
      --listen-gossip 0.0.0.0:9656
      --listen-http 0.0.0.0:9666
    depends_on:
      - postgresql
    environment:
      HAB_AUTOMATE_NGINX: |
        port = ${PILOT_HTTP_PORT:-8080}
        ssl_port = ${PILOT_HTTPS_PORT:-8443}
    volumes:
      - ${DATA_MOUNT:-/mnt/hab}/maintenance:/var/opt/delivery/delivery/etc
      - ${DATA_MOUNT:-/mnt/hab}/nginx:/hab/svc/automate-nginx/data:Z
